### ISSUE TITLE
Задачки на багам

### ISSUE THREAD

**Issue by welldone-tomato** [kroniak/yandex-wallet#10]
**переменные окружения ENV**
- [x] test_helper.js ссылается на докер вместо единой переменной
хорошо бы иметь один настроечный конфиг файл #9 

**транзакции создается, но не должна в случаях:**

- [x] если у нас некорректный номер карты - вываливается ошибка, но транза создается
- [x] если у нас 2 карты с одинаковыми номерами, будет ошибка, но транса все равно создастся

**папка с сертификатом и ключом** 
- [x] должна лежать в папке ssl и обновить файл генерации ssl #9

**скачивание csv не работает**
- [ ] ошибка {"message":"auth is required"} скорее всего из-за отсутствия заголовка  authorization:JWT...

**Comment by kroniak** [comment]
2.2 поясни, что это за кейс

**Comment by kroniak** [comment]
И пункт 2.1 тоже поясни, не очень ясно

**Comment by welldone-tomato** [comment]
когда я создаю транзакцию с карты другого пользователя, которая имеет точно такой же номер - вываливается ошибка, но транзакция создается

Аналогично в другом кейсе.

1й кейс только что смог повторить
2й - почему-то база не дает сохранить 2 карты с одинак номерами. А изначально получилось точно. Я просто скопировал и вставил

**Comment by kroniak** [comment]
@welldone-tomato фикс = #11 
Работая над фиксом, реализовал мини транзакционность: если после создания транзакции в следующих действиях что то происходит, то транзакция помечается как ошибочная. В ui она отображается красной и показывается подсказка о чем вообще речь.
