### ISSUE TITLE
Идеи к командной работе

### ISSUE THREAD

**Issue by kroniak** [kroniak/yandex-wallet#6]
Репозиторий для начальной работы master.
Все добавления путем PR в ветку master.
Для обсуждения по каждой задачи можно создавать свой issue.

**Дополнения, уже реализованые:**
Сервер:
- Авторизация Jwt,  модель пользователя в базе.
- Тесты 100% контроллера, моделей и валидация полная

Клиент:
- Авторизация
- redux,  re-select.
- Сценарии ошибок внутри платежей,  переводов и т.п.
- Разбивка таблицы истории по датам.

**Что бы хотелось бы реализовать:**
- Сценарий добавления новой карты с валидацией и автоматическим подтягиванием UI по номер карты
- Автообновление данные карт в фоновом режиме через sockets
- Проверка номера сотового оператора
- Сохранение состояния в localstorage + PWA

**Comment by Punxnot** [comment]
Ещё идеи: 
- Поиск ближайшего банкомата
- Статистика использования карт

**Comment by kroniak** [comment]
Еще идея:

Добавление еще одного типа транзакции card2user, т.к. у нас разные пользователи в приложении, т.е. можно реализовать механизм перевода на карту другого пользователя. Так же фича, связанная с этим же сценарием, но удобнее в использовании и на мой взгляд : кандидат номер 1:

на каждой карте кнапка-иконка запроса денег и "расшаривания" своей карты для переводов. При нажатии на "запрос денег" всплывает окно с выбором карты и суммы, на выходе формы получается ссылка, по которой другой пользователь приложения может со своей карты перевести нужную сумму владельцу ссылки.

Если как то неясно написал, спрашивайте.

**Comment by Punxnot** [comment]
Ещё идея: сделать локализацию (хотя бы русский/английский)

**Comment by kuhel** [comment]
**Анализ расходов**
- Выборка по типам транзакций
- Выборка по карточкам

**Цели**
- Постановка цели в виде суммы для накопления
- Автоплатеж с выбором периода

**Курсы Валют**
- Использовать внешний API на вьюхе, либо проксировать через свое приложение на сервере 

**Шаблоны типичных операций**

- Для часто повторяющихся операций создавать шаблоны с быстрым доступом

**Автоплатежи**

- Настраиваемые автоплатежи

**Push уведомления**

- Например о поступлениях/списаниях

**История операций**

**Comment by dazzlegit** [comment]
Возможность создавать валютные карты, перевод между картами разных валют с учетом актуального курса, какой-то комиссии.

Покупка товаров из некоторого списка от "партнеров", с начислением бонусов за покупку, которыми потом можно возместить стоимость других покупок.

**Comment by kuhel** [comment]
**UI**

- Допилить удаление/добавление карт

**Comment by kuhel** [comment]
**Долги** 
- Кто сколько должен плюс напоминания о просроченных долгах

**Семейный доступ** 
- Возможность выдать доступ к карте другому юзеру, но с ограничениями (то есть доступ только к конкретным картам, с лимитом на расход по карте)
- оповещения о транзакциях членов семьи
